### ISSUE TITLE
Duplicated uas, vas for CUNI_WRF451R-SFNO

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/STAGE-0_Analysis#14]
`uas` and `vas` variables are missing for WRF451R-SFU1. The files for CUNI_WRF451R-SFNO are duplicated in the corresponding folder:

![image](https://github.com/user-attachments/assets/13bdb085-320f-4d9d-ade7-8f1b11b6591d)

**Comment by jesusff** [comment]
ping @anvipra

**Comment by anvipra** [comment]
solved :)

**Comment by jesusff** [comment]
Thank you!
