### ISSUE TITLE
AUTH had 2 sets of postprocessed data, the wrong one should be deleted

### ISSUE THREAD

**Issue by yoselita** [FPS-URB-RCC/STAGE-0_Analysis#21]
AUTH has data postprocessed in May and August (v20240527  v20240828). My guess is that the data postprocessed in May are the data with the cold-pools bug that we fixed in the meanwhile. If so, I would suggest to delete the data as they should not be used in the analyses.

**Comment by vpavli** [comment]
I have deleted the v20240527 data.

**Comment by vpavli** [comment]
Thanks @yoselita for bringing this out.
