### ISSUE TITLE
CMCC institution_model split missing

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/STAGE-0_Analysis#6]
> collected from Michal's presentation on Stage-0 evaluation:

CLMcom-CMCC-ICONCLM2-6-6 not according to protocol (institution_model split missing in filenames)

**Comment by jesusff** [comment]
This is partly fixed, but in the directory name the problem remains:
https://github.com/FPS-URB-RCC/STAGE-0_Analysis/blob/0265a89106bc1852d9a805bbc8564bafc184ba27/list_server_files__pr_1hr.txt#L33C48-L33C72
Also for CLMcom-CMCC_CCLM6-0-1

**Comment by ma-cmcc** [comment]
Hi Jesus ... apologies for the delayed response. Does this issue still persist? I cheched on Levante but I couldn't find the institution_model split missing, either in the filename variables or in the directory name. 
This I can see for CCLM6-0-1:
![CCLM6-0-1](https://github.com/user-attachments/assets/1460bfb7-6889-4a52-b8ab-0d7188f07b51)
This I can see for ICONCLM2-6-6:
![ICONCLM2-6-6](https://github.com/user-attachments/assets/e9db7223-e883-475a-8b1d-759ff97b288b)
Do I miss something?
Thanks a lot,
Marianna

**Comment by jesusff** [comment]
Hi Marianna,

yes, in the path there should be no underscore. The ˋinstitution_idˋ and ˋsource_idˋ elements are different separate folders. E.g., this path:

ˋ./PARIS-3/CLMcom-CMCC/ERA5/evaluation/r1i1p1f1/CLMcom-CMCC_ICONCLM2-6-6/v1-fpsurbrcc-s0r1/1hr/prˋ

should read:

ˋ./PARIS-3/CLMcom-CMCC/ERA5/evaluation/r1i1p1f1/ICONCLM2-6-6/v1-fpsurbrcc-s0r1/1hr/prˋ

Filenames are OK, except that you uploaded a much longer period than requested, up to the end of the year. Also CCLM starts in April and ICON in May. Was April the spin-up month for CCLM? (see #3 )

**Comment by ma-cmcc** [comment]
Hi Chus,
thanks for the clarification. Now the paths should be fine.
No, for CCLM we started the run at the beginning of 2020 so we could consider 3 months spin-up period (untill march).
Thanks a lot for your effort.
Cheers,
M

**Comment by jesusff** [comment]
Thanks!

Please, note also the missing version folder (#11). I close this issue.
