### ISSUE TITLE
wrong aggregation of daily variables

### ISSUE THREAD

**Issue by anacv** [FPS-URB-RCC/STAGE-0_Analysis#9]
Daily tasmin and tasmax have one single time step in UCAN simulations (EUR-12 and PARIS-3)

**Comment by yoselita** [comment]
Thank you @anacv for finding this out. The daily aggregation performed with [cdo](https://code.mpimet.mpg.de/projects/cdo/wiki) was done wrong, as the time dimension in the source file was not correctly set. This has been fixed now and the fixed files are updated for all the UCAN experiment in the DKRZ for both domain. Note, that the old files have been replaced with the new files, to avoid confusion.
